image: docker.io/qazando/appium-maven

stages:
  - test

th-job:       
  stage: test
  script:
    - curl -Ls "https://get.maestro.mobile.dev" | bash
    - export PATH="$PATH:$HOME/.maestro/bin"
    - maestro cloud --apikey rb_vjD2WIqEVTRyeDis5cbbtCO2jijodytDqJmKxKhavK8yuuMLRIWHBmPtAnuqSPreQ4DR9O2svFE4OE2DVNysv560huCDJesucPn progic_app.apk .maestro/
