name: Build
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Baixar e instalar o Maestro
      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
      
      # Exportar chave API e Project ID do Maestro
      - name: Set Environment Variables
        run: |
          echo "MAESTRO_API_KEY=${{ secrets.MAESTRO_API_KEY }}" >> $GITHUB_ENV
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> $GITHUB_ENV
      
      # Rodar testes usando o Maestro
      - name: Run Maestro Tests
        run: |
          maestro cloud --apiKey $MAESTRO_API_KEY --project-id $PROJECT_ID progic_app.apk .maestro/