name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: docker.io/cypress/browsers

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: mobile-dev-inc/action-maestro-cloud@v1.1.0
        with:
          api-key: c1dcb074-3954-4447-aa0e-78a4df3b092e
          app-file: progic_app.apk